name       : xorg-driver-video-savage
version    : 2.3.9
release    : 5
source     :
    - git|https://gitlab.freedesktop.org/xorg/driver/xf86-video-savage.git : 0ece556daa8a88771b669d8104396abd9166d2d0
license    : MIT
component  : xorg.driver
optimize   :
    - no-bind-now
    - no-symbolic
summary    : Savage Video Driver
description: |
    The Xorg Savage Driver package contains the X.Org Video Driver for the S3 Savage family video accelerator chips including Savage3D, Savage4, Savage/MX, Savage/IX, SuperSavage/MX, SuperSavage/IX, ProSavage PM133, ProSavage KM133, Twister, TwisterK, ProSavage DDR and ProSavage DDR-K series.
builddeps  :
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
    - pkgconfig(xorg-macros)
    - pkgconfig(xorg-server)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
