name       : xorg-driver-video-savage
version    : 2.3.9
release    : 3
source     :
    - https://www.x.org/archive/individual/driver/xf86-video-savage-2.3.9.tar.bz2 : 2c93c4db1f71e725dda0caee5821253129d4b52d7aa0fd720593e7769bceec86
license    : MIT
component  : xorg.driver
optimize   :
    - no-bind-now
    - no-symbolic
summary    : Savage Video Driver
description: |
    The Xorg Savage Driver package contains the X.Org Video Driver for the S3 Savage family video accelerator chips including Savage3D, Savage4, Savage/MX, Savage/IX, SuperSavage/MX, SuperSavage/IX, ProSavage PM133, ProSavage KM133, Twister, TwisterK, ProSavage DDR and ProSavage DDR-K series.
builddeps  :
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
    - pkgconfig(xorg-macros)
    - pkgconfig(xorg-server)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
